version: "3.8"

services:
  postgres:
    image: kartoza/postgis:13.0
    networks:
      - roadtrip-net
    ports:
      - 5432:5432
    volumes:
      - roadtrip-db:/var/lib/postgresql
    environment:
      - ALLOW_IP_RANGE=0.0.0.0/0
    restart: on-failure

  roadtrip:
      build: ./app
      volumes:
          - ./app:/app
          - ./data:/data
      ports:
          - 80:80
      networks:
          - roadtrip-net
      environment:
          - FLASK_APP=main.py
          - FLASK_DEBUG=1
      env_file: 
          - ./.env
      command: flask run --host=0.0.0.0 --port=80
      # command: python /app/pipeline.py
      # below doesn't appear to work
      # command: python /app/pipeline.py && flask run --host=0.0.0.0 --port=80 

volumes:
    roadtrip-db:
    
networks:
    roadtrip-net:
        driver: bridge